config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :people

  root 'groups#index'
  get 'aleatoire' => 'groups#Rand'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :people
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :unminimumgroupe, only: [:Rand]
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @people = Person.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to root_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
# création de l'algo permettant de lancer le random
  # def Rand
  #   @people = Person.all
  #   @groups = Group.all
  #
  #   maxByGroup = (@people.size / @groups.size).ceil + 1
  #
  #   @people.each do |person|
  #     person.group_id = nil
  #     person.save
  #   end
  #
  #   id_Group = []
  #
  #   @groups.each do |group|
  #     id_Group << group.id
  #   end
  #
  #
  #   @people.each do |i|
  #     random_groupe = id_Group.sample
  #     i.group_id = random_groupe
  #     i.save
  #     if @people.where(group_id: random_groupe).size == maxByGroup
  #       id_Group.delete(random_groupe)
  #     end
  #   end
  #   redirect_to root_path
  # end
  def Rand
    @people = Person.all

    @people.each do |person|
    person.sensei = false
    person.save
 end
   idperson = Person.all.map{|x| x.id}
   if Group.all.count>0
     while idperson.count >0
       Group.all.each do |grp|
         a = idperson.sample
         Person.find(a).update_attributes(group_id: grp.id) unless a.nil?
         ## summarize that:
         # b = Person.find(a)
         # b.group_id = grp.id
         # b.save
         idperson.delete(a)
       end
     end
     else
       redirect_to :root, notice: "ther have to be a least one group"
     end
     redirect_to :root, notice: "Yataî  all has been randomized!!!"
 end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :salle, :tache)
    end

    def unminimumgroupe
      if Group.all.size < 2
        redirect_to root_path, notice: 'Vous devez au minimum créer deux groupes'
      end
    end



end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
 before_action :set_person, only: [:show, :edit, :update, :destroy]  # GET /people
 # GET /people.json
 def index
   @people = Person.all
 end
 # GET /people/1
 # GET /people/1.json
 def show
 end  # GET /people/new

 def new
   @person = Person.new
 end  # GET /people/1/edit

 def edit
 end

 # POST /people
 # POST /people.json
 def create
   @person = Person.new(person_params)
   respond_to do |format|
     if @person.save
       format.html { redirect_to root_path, notice: 'Person was successfully created.' }
       format.json { render :show, status: :created, location: @person }
     else
       format.html { render :new }
       format.json { render json: @person.errors, status: :unprocessable_entity }
     end
   end
 end  # PATCH/PUT /people/1
 # PATCH/PUT /people/1.json
 def update
   respond_to do |format|
     if @person.update(person_params)
       format.html { redirect_to root_path, notice: 'Person was successfully updated.' }
       format.json { render :show, status: :ok, location: @person }
     else
       format.html { render :edit }
       format.json { render json: @person.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /people/1
 # DELETE /people/1.json
 def destroy
   @person.destroy
   respond_to do |format|
     format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private

   # Use callbacks to share common setup or constraints between actions.
   def set_person
     @person = Person.find(params[:id])
   end
   # Never trust parameters from the scary internet, only allow the white list through.
   def person_params
     params.require(:person).permit(:name, :email, :tel, :group_id, :sensei)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
     { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
   end
   def flash_messages(opts = {})
     flash.each do |msg_type, message|
       concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
                concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                         concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                         concat content_tag(:span, 'Close', class: 'sr-only')
                end)
                concat message
       end)
     end
     nil
   end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
<% if @group.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@group.errors.count, "error") %>
    prohibited this group from being saved:</h2>

  <ul>
    <% @group.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="container">
  <div class="row col-md-offset-4">

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :salle %><br>
      <%= f.text_field :salle %>
    </div>
    <div class="field">
      <%= f.label :tache %><br>
      <%= f.text_area :tache %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
</div>
<% end %>

app/views/groups/edit.html.erb
<div class="container">


<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>
</div>

app/views/groups/index.html.erb
<div class="container">

  <h1>Organization</h1>
  <div class="row">

    <% @groups.each do |group| %>
    <div class="col-md-2 inline">
      <strong><%= group.name %>
        <%= group.salle %>
        <%= group.tache %></strong>
      <br>
      <div>
        <% @people.each do |gens|%>
        <% if group.id == gens.group_id %>
        <br><%= best_in_place gens, :name%>
        <%= best_in_place gens, :sensei, :as => :select, :collection => {"1" => "Sensei"} %>
        <% end %>

        <% end %>
      </div>
      <br>

      <span class="glyphicon glyphicon-pencil"> <%= link_to 'Edit', edit_group_path(group) %></span>
      <span class="glyphicon glyphicon-trash"> <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    </div>
    <% end %>
  </div>

<br>
  <div class="the_new_group"><span class="glyphicon glyphicon-plus-sign"><%= link_to 'New Group', new_group_path %></span></div>

  <br>

  <h1>Listing People</h1>

  <div id="butn"><span class="glyphicon glyphicon-refresh"><%= link_to 'Random', aleatoire_path %></span></div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <!-- <th>Email</th> -->
        <!-- <th>Tel</th> -->
        <!-- <th>Group</th> -->
        <th>Sensei</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <!-- <td><%= person.email %></td> -->
        <!-- <td><%= person.tel %></td> -->
        <!-- <td><%= person.group_id %></td> -->
        <td><%= person.sensei %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<script type="text/javascript">
  $(document)
    .ready(function () {
      /* Activating Best In Place */
      $(".best_in_place").best_in_place();
    });
</script>

app/views/groups/new.html.erb
<div class="container">


<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Randomhachemi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
   <div class="container">
     <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-home">HOME</span></a>
     </div>
     <div class="collapse navbar-collapse" id="myNavbar">
       <ul class="nav navbar-nav navbar-right">
         <li><a href="#">Try</a></li>
         <li><a href="#">Try again</a></li>
         <li><a href="#">Again N' Again</a></li>
       </ul>
     </div>
   </div>
 </nav>
   <div class="message"> <%= flash_messages %></div>
<%= yield %>
<br>
<br>
<footer class="footer">
    <div class="container">

    </div>
</footer>
</body>
</html>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>



<div class="container">
<h1>Listing People</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th>Group</th>
      <th>Sensei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td>0<%= person.tel %></td>
        <td><%= person.group_id %></td>
        <td><%= person.sensei %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">


<p>
  <strong>Nom:</strong>
  <%= @person.nom %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @person.tel %>
</p>

<p>
  <strong>Group:</strong>
  <%= @person.group_id %>
</p>

<p>
  <strong>Sensei:</strong>
  <%= @person.sensei %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>
</div>